-- ******************************************************************
--
-- (C) COPYRIGHT IBM CORPORATION 2010, 2025.
--     Copyright Contributors to the GenevaERS Project.
-- SPDX-License-Identifier: Apache-2.0
--
-- ******************************************************************
--
--   Licensed under the Apache License, Version 2.0 (the "License");
--   you may not use this file except in compliance with the License.
--   You may obtain a copy of the License at
--
--      http://www.apache.org/licenses/LICENSE-2.0
--
--   Unless required by applicable law or agreed to in writing, software
--   distributed under the License is distributed on an "AS IS" BASIS,
--   WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
--   or implied.
--   See the License for the specific language governing permissions
--   and limitations under the License.
--
-- ****************************************************************
--

  DROP PROCEDURE  CLEARENVIRON;  
  DROP PROCEDURE  DELETEENVIRON; 
  DROP PROCEDURE  ENVDEPENDENCY; 
  DROP PROCEDURE  ENVINITVALUES; 
  DROP PROCEDURE  GETCOMPDEPS;   
  DROP PROCEDURE  GETVIEWPROPS;  
  DROP PROCEDURE  GETVERSION;    
  DROP PROCEDURE  INSLPSRCFLD;   
  DROP PROCEDURE  INSLRFIELD;    
  DROP PROCEDURE  INSSECGRPRGHT; 
  DROP PROCEDURE  INSVIEWCOL;    
  DROP PROCEDURE  INSVIEWCOLSRC; 
  DROP PROCEDURE  UPDLRFIELD;    
  DROP PROCEDURE  UPDVIEWCOL;    
  DROP PROCEDURE  UPDVIEWCOLSRC; 
  DROP PROCEDURE  UPDVWLOGIC;    
  DROP PROCEDURE  GETDEPSEXIT;   
  DROP PROCEDURE  GETDEPSFIELD;  
  DROP PROCEDURE  GETDEPSLF;     
  DROP PROCEDURE  GETDEPSLP;     
  DROP PROCEDURE  GETDEPSLR;     
  DROP PROCEDURE  GETDEPSPF;     
  DROP PROCEDURE  GETDEPSVIEW;   
  DROP PROCEDURE  GENLFDEPS;     
  DROP PROCEDURE  GENLPDEPS;     
  DROP PROCEDURE  GENLRDEPS;     
  DROP PROCEDURE  GENPFDEPS;     
  DROP PROCEDURE  GENVIEWDEPS;
